### ISSUE TITLE
Read about the site

### ISSUE THREAD

**Issue by petermcloughlin** [petermcloughlin/django-blog#10]
As a **Site User** I can **click on the About link** so that **I can read about the site**

- When the About link is clicked, the about text is visible.

**Comment by Felipe-Rafael-Rosa** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
